### ISSUE TITLE
Gmaps

### ISSUE THREAD

**Issue by Pavithrashanthi** [Pavithrashanthi/WhatsUp-Developement#4]
Add Gmaps to search user current location

**Comment by Pavithrashanthi** [comment]
Check with team and add Gmap

**Comment by Pavithrashanthi** [comment]
@Pavithrashanthi Feature has been taken. I'll inform you once it is done

**Comment by karthik** [comment]
Wrong person.

**Comment by Pavithrashanthi** [comment]
Apologize. Please ignore
